// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';
// Sidebar / curriculum structure for the /ai/ guide. GENERATED by
// `npm run import:guide` from the source-of-truth repo (bryanpcutsinger/
// claude-code-guide); do not hand-edit — edit guide.manifest.json there + re-import.
import claudeGuideSidebar from './src/data/guide-sidebar.json';

// Defense-in-depth: strip HTML comments (incl. the `<!-- INSTRUCTOR NOTES -->`
// block) from imported course posts at render time. The PRIMARY strip is
// scripts/import-topic.sh (so notes never enter this public repo's source); this
// is a backstop, plus the `postbuild` grep gate in package.json. Scoped to
// /content/courses/ by file path so Starlight's /ai/ docs are untouched. Never
// throws — a failure here must not break the build (the import script already
// guaranteed clean source).
function stripCourseComments() {
  const COMMENT = /<!--[\s\S]*?-->/g;
  return (/** @type {any} */ tree, /** @type {any} */ file) => {
    const path = file?.path || file?.history?.[0] || '';
    if (!String(path).includes('/content/courses/')) return;
    const walk = (/** @type {any} */ node) => {
      if (!node || !Array.isArray(node.children)) return;
      node.children = node.children.filter((/** @type {any} */ child) => {
        if (child.type === 'html' && typeof child.value === 'string') {
          child.value = child.value.replace(COMMENT, '');
          if (child.value.trim() === '') return false; // drop emptied node
        }
        walk(child);
        return true;
      });
    };
    try {
      walk(tree);
    } catch {
      /* never throw — import-topic.sh is the primary control */
    }
  };
}

// GitHub *user site* (bryanpcutsinger.github.io) served from root — no `base`.
// The site is a Starlight docs site themed to the FAU style guide (see
// src/styles/fau-theme.css). When a custom domain is attached, only `site` changes.
export default defineConfig({
  site: 'https://bryancutsinger.com',
  // Backstop strip for imported course posts (see stripCourseComments above).
  // The path guard makes it a no-op for every non-course file, so the /ai/
  // Starlight build output is byte-for-byte unchanged.
  markdown: { remarkPlugins: [stripCourseComments] },
  integrations: [
    // Explicit sitemap so the custom marketing pages (src/pages/*) are included
    // — Starlight's transitive sitemap only enumerates its own docs routes.
    sitemap(),
    starlight({
      title: 'Bryan Cutsinger',
      // TEMP: keep the site out of search results while it's shared privately with a
      // colleague (deploy-ready, not a public announcement). Delete this `head` block
      // to allow search engines to index the site at full public launch.
      head: [
        { tag: 'meta', attrs: { name: 'robots', content: 'noindex, nofollow' } },
      ],
      description:
        'A beginner\'s guide to getting started with Claude Code for teaching and research, plus notes on using AI.',
      // FAU style-guide theming layered on top of Starlight's tokens.
      customCss: ['./src/styles/fau-theme.css'],
      // Keep Bryan's own identity in the chrome (no FAU logo/wordmark); the
      // Footer override WRAPS the default so the prev/next pager is preserved.
      components: {
        SiteTitle: './src/components/overrides/SiteTitle.astro',
        Footer: './src/components/overrides/Footer.astro',
        // Repurpose the (empty) social-icons header slot for nav links back to
        // the marketing site, keeping both systems navigable.
        SocialIcons: './src/components/overrides/HeaderLinks.astro',
      },
      // Curriculum order + grouping now live in the GUIDE repo
      // (guide.manifest.json), imported above as `claudeGuideSidebar` and written
      // to src/data/guide-sidebar.json by `npm run import:guide`. To change the
      // sidebar (add posts, restore the "Set up / Get oriented / Reference"
      // groups), edit the manifest in bryanpcutsinger/claude-code-guide and
      // re-import — NOT here. Draft-safety rule: the manifest lists only
      // draft:false posts (Starlight fails the build on draft/missing slugs).
      sidebar: [claudeGuideSidebar],
      // No social/edit links or last-updated for now; keep it clean.
      lastUpdated: false,
      pagination: true,
      // Remove the search box (Starlight's built-in Pagefind UI + ⌘K modal).
      pagefind: false,
    }),
  ],
});
